FROM golang:1.13-alpine3.10 AS builder

ARG VERSION

RUN set -eux \
	&& apk --no-cache add \
		g++ \
		gcc \
		git \
		make \
		musl-dev

COPY . /sandbox/istio
WORKDIR /sandbox/istio

RUN make echod

FROM alpine:3.10

COPY --from=builder /sandbox/istio/echod /usr/local/bin/echod

RUN apk --no-cache add \
	ca-certificates \
	curl \
	bind-tools

EXPOSE 5000

RUN addgroup -g 1000 -S app && \
    adduser -u 1000 -S app -G app
USER app

ENTRYPOINT ["echod"]
