FROM golang:1.13-alpine3.10 AS builder

ARG VERSION

RUN set -eux \
	&& apk --no-cache add \
		g++ \
		gcc \
		git \
		make \
		musl-dev

COPY . /sandbox/istio/hello
WORKDIR /sandbox/istio/hello

RUN make echo2d

FROM alpine:3.10

COPY --from=builder /sandbox/istio/hello/echo2d /usr/local/bin/echo2d

RUN apk --no-cache add \
	ca-certificates \
	curl

EXPOSE 5000

RUN addgroup -g 1000 -S app && \
    adduser -u 1000 -S app -G app
USER app

ENTRYPOINT ["echo2d"]
